[package]
name = "gribberish_python"
version = "0.20.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "gribberish_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.0"
gribberish = { path = "../gribberish" }
numpy = "0.21.0"
