[package]
name = "grib-dump"
version = "0.1.0"
authors = ["Matthew Iannucci <mpiannucci@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grib = { path = "../grib" }
chrono = "0.4"